version: 2.1

orbs:
  rn: react-native-community/react-native@7.4.0

jobs:
  checkout_code:
    executor:
      name: rn/linux_js
      node_version: '20.11'
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: .
  analyse:
    executor: 
      name: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - rn/yarn_install
      - run:
          name: Lint JS Code (ESLint)
          command: yarn run lint
      - run:
          name: Jest
          command: yarn run test

workflows:
  test:
    jobs:
      - checkout_code
      - analyse:
          requires:
            - checkout_code
      - rn/android_build:
          name: build_android_debug
          attach_workspace: true
          workspace_root: "example"
          build_type: debug
          requires:
            - analyse
      - rn/android_build:
          name: build_android_release
          attach_workspace: true
          workspace_root: "example"
          build_type: release
          requires:
            - analyse
#      - rn/android_test:
#          detox_configuration: "android.emu.release"
#          detox_loglevel: "trace"
#          requires:
#            - build_android_release
